import React from 'react'

const Groups = () => {
  return (
    <div>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>
    <h1>Groups</h1>DD
    </div>
  )
}

export default Groups