export const modulesData = [
    { id: 1, title: "Introduction to Programming", code: "COMP101", short: "IP", teachingMode: "Lecture" },
    { id: 2, title: "Mathematics I", code: "MATH101", short: "MT1", teachingMode: "Lab" },
    { id: 3, title: "English Composition", code: "ENG101", short: "EC", teachingMode: "Lecture" },
    { id: 4, title: "Data Structures", code: "COMP201", short: "DS", teachingMode: "Lab" },
    { id: 5, title: "Physics for Engineers", code: "PHYS101", short: "PE", teachingMode: "Lecture" },
    { id: 6, title: "Algorithm Design", code: "COMP202", short: "AD", teachingMode: "Lab" },
    { id: 7, title: "Linear Algebra", code: "MATH201", short: "LA", teachingMode: "Lecture" },
    { id: 8, title: "English Literature", code: "ENG201", short: "EL", teachingMode: "Lecture" },
    { id: 9, title: "Web Development", code: "COMP203", short: "WD", teachingMode: "Workshop" },
    { id: 10, title: "Statistics", code: "MATH202", short: "STAT", teachingMode: "Lab" },
    { id: 11, title: "Operating Systems", code: "COMP204", short: "OS", teachingMode: "Lecture" },
    { id: 12, title: "Artificial Intelligence", code: "COMP301", short: "AI", teachingMode: "Lab" },
    { id: 13, title: "Ethics in Technology", code: "ETH101", short: "ETH", teachingMode: "Lecture" },
    { id: 14, title: "Differential Equations", code: "MATH203", short: "DE", teachingMode: "Lecture" },
    { id: 15, title: "Database Management", code: "COMP302", short: "DBM", teachingMode: "Workshop" },
    { id: 16, title: "French Language", code: "LANG101", short: "FL", teachingMode: "Lecture" },
    { id: 17, title: "Computer Networks", code: "COMP303", short: "CN", teachingMode: "Lab" },
    { id: 18, title: "Psychology", code: "PSYCH101", short: "PSY", teachingMode: "Lecture" },
    { id: 19, title: "Software Engineering", code: "COMP304", short: "SE", teachingMode: "Lab" },
    { id: 20, title: "Environmental Science", code: "ENVSCI101", short: "ES", teachingMode: "Lecture" },
    { id: 21, title: "Human-Computer Interaction", code: "COMP401", short: "HCI", teachingMode: "Lab" },
    { id: 22, title: "Spanish Literature", code: "LANG201", short: "SL", teachingMode: "Lecture" },
    { id: 23, title: "Mobile App Development", code: "COMP402", short: "MAD", teachingMode: "Workshop" },
    { id: 24, title: "Calculus II", code: "MATH204", short: "CALCII", teachingMode: "Lecture" },
    { id: 25, title: "Computer Graphics", code: "COMP403", short: "CG", teachingMode: "Lab" },
    { id: 26, title: "History of Science", code: "HISTSCI101", short: "HS", teachingMode: "Lecture" },
    { id: 27, title: "Cybersecurity", code: "COMP404", short: "SEC", teachingMode: "Lab" },
    { id: 28, title: "Philosophy", code: "PHIL101", short: "PHIL", teachingMode: "Lecture" },
    { id: 29, title: "Robotics", code: "COMP501", short: "ROBO", teachingMode: "Lab" },
    { id: 30, title: "Astronomy", code: "ASTRO101", short: "ASTRO", teachingMode: "Lecture" },
    { id: 31, title: "Capstone Project", code: "COMP505", short: "CAP", teachingMode: "Workshop" }
  ];


 
  export const workLoads = [
    { id: 1, moduleCode: "CSC2022", moduleName: "Database Management System", department: "ICT", program: "Software Design", group: "Year1" },
    { id: 2, moduleCode: "MTH101", moduleName: "Mathematics I", department: "Mathematics", program: "Applied Mathematics", group: "Year2" },
    { id: 3, moduleCode: "PHY201", moduleName: "Physics II", department: "Physics", program: "Physics", group: "Year3" },
    { id: 4, moduleCode: "ENG303", moduleName: "Technical Writing", department: "English", program: "Technical Communication", group: "Year4" },
    { id: 5, moduleCode: "CSC404", moduleName: "Advanced Algorithms", department: "ICT", program: "Software Engineering", group: "Year2" },
    { id: 6, moduleCode: "CHE201", moduleName: "Chemistry I", department: "Chemistry", program: "Chemical Engineering", group: "Year3" },
    { id: 7, moduleCode: "BIO101", moduleName: "Biology Basics", department: "Biology", program: "Biomedical Science", group: "Year1" },
    { id: 8, moduleCode: "BUS202", moduleName: "Management Principles", department: "Business", program: "Business Administration", group: "Year4" },
    { id: 9, moduleCode: "CSC505", moduleName: "Machine Learning", department: "ICT", program: "Data Science", group: "Year2" },
    { id: 10, moduleCode: "ENG101", moduleName: "Introduction to Literature", department: "English", program: "English Literature", group: "Year1" },
    { id: 11, moduleCode: "PHY303", moduleName: "Quantum Mechanics", department: "Physics", program: "Physics", group: "Year3" },
    { id: 12, moduleCode: "MKT404", moduleName: "Marketing Strategies", department: "Business", program: "Marketing", group: "Year4" },
    { id: 13, moduleCode: "CSC606", moduleName: "Web Development", department: "ICT", program: "Computer Science", group: "Year2" },
    { id: 14, moduleCode: "ENG202", moduleName: "Creative Writing", department: "English", program: "Creative Writing", group: "Year1" },
  ];
  