export const modulesData = [
    { id: 1, title: "Introduction to Programming", code: "COMP101", short: "IP", teachingMode: "Lecture" },
    { id: 2, title: "Mathematics I", code: "MATH101", short: "MT1", teachingMode: "Lab" },
    { id: 3, title: "English Composition", code: "ENG101", short: "EC", teachingMode: "Lecture" },
    { id: 4, title: "Data Structures", code: "COMP201", short: "DS", teachingMode: "Lab" },
    { id: 5, title: "Physics for Engineers", code: "PHYS101", short: "PE", teachingMode: "Lecture" },
    { id: 6, title: "Algorithm Design", code: "COMP202", short: "AD", teachingMode: "Lab" },
    { id: 7, title: "Linear Algebra", code: "MATH201", short: "LA", teachingMode: "Lecture" },
    { id: 8, title: "English Literature", code: "ENG201", short: "EL", teachingMode: "Lecture" },
    { id: 9, title: "Web Development", code: "COMP203", short: "WD", teachingMode: "Workshop" },
    { id: 10, title: "Statistics", code: "MATH202", short: "STAT", teachingMode: "Lab" },
    { id: 11, title: "Operating Systems", code: "COMP204", short: "OS", teachingMode: "Lecture" },
    { id: 12, title: "Artificial Intelligence", code: "COMP301", short: "AI", teachingMode: "Lab" },
    { id: 13, title: "Ethics in Technology", code: "ETH101", short: "ETH", teachingMode: "Lecture" },
    { id: 14, title: "Differential Equations", code: "MATH203", short: "DE", teachingMode: "Lecture" },
    { id: 15, title: "Database Management", code: "COMP302", short: "DBM", teachingMode: "Workshop" },
    { id: 16, title: "French Language", code: "LANG101", short: "FL", teachingMode: "Lecture" },
    { id: 17, title: "Computer Networks", code: "COMP303", short: "CN", teachingMode: "Lab" },
    { id: 18, title: "Psychology", code: "PSYCH101", short: "PSY", teachingMode: "Lecture" },
    { id: 19, title: "Software Engineering", code: "COMP304", short: "SE", teachingMode: "Lab" },
    { id: 20, title: "Environmental Science", code: "ENVSCI101", short: "ES", teachingMode: "Lecture" },
    { id: 21, title: "Human-Computer Interaction", code: "COMP401", short: "HCI", teachingMode: "Lab" },
    { id: 22, title: "Spanish Literature", code: "LANG201", short: "SL", teachingMode: "Lecture" },
    { id: 23, title: "Mobile App Development", code: "COMP402", short: "MAD", teachingMode: "Workshop" },
    { id: 24, title: "Calculus II", code: "MATH204", short: "CALCII", teachingMode: "Lecture" },
    { id: 25, title: "Computer Graphics", code: "COMP403", short: "CG", teachingMode: "Lab" },
    { id: 26, title: "History of Science", code: "HISTSCI101", short: "HS", teachingMode: "Lecture" },
    { id: 27, title: "Cybersecurity", code: "COMP404", short: "SEC", teachingMode: "Lab" },
    { id: 28, title: "Philosophy", code: "PHIL101", short: "PHIL", teachingMode: "Lecture" },
    { id: 29, title: "Robotics", code: "COMP501", short: "ROBO", teachingMode: "Lab" },
    { id: 30, title: "Astronomy", code: "ASTRO101", short: "ASTRO", teachingMode: "Lecture" },
    { id: 31, title: "Capstone Project", code: "COMP505", short: "CAP", teachingMode: "Workshop" }
  ];


 
export const TABLE_ROWS = [
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
    name: "Spotify",
    amount: "$2,500",
    date: "Wed 3:00pm",
    status: "paid",
    account: "visa",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    amount: "$5,000",
    date: "Wed 1:00pm",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
    name: "Pinterest",
    amount: "$3,400",
    date: "Mon 7:40pm",
    status: "pending",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-google.svg",
    name: "Google",
    amount: "$1,000",
    date: "Wed 5:00pm",
    status: "paid",
    account: "visa",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-netflix.svg",
    name: "netflix",
    amount: "$14,000",
    date: "Wed 3:30am",
    status: "cancelled",
    account: "visa",
    accountNumber: "1234",
    expiry: "06/2026",
  },
];